### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by esokullu** [polygonplanet/Posql#1]
Hello,

Interesting project. What is the license?

Thank you,

**Comment by esokullu** [comment]
If it's MIT, we could use it with [phonetworks](https://github.com/phonetworks) as a pure php backend adapter.

**Comment by polygonplanet** [comment]
Thanks!
This project is licensed under a dual license system (MIT or GPL v2). [source comment](https://github.com/polygonplanet/Posql/blob/master/src/posql.php#L24)
This means you are free to choose with which of both licenses (MIT or GPL v2) you want to use this library.
But, this library is very old. may not work in PHP 7+.

**Comment by esokullu** [comment]
Thank you! will examine more throughly now and report about PHP 7 compat.
Cheers,
